export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_REQUEST_FAIL = "USERS_REQUEST_FAIL";
export const USERS_REQUEST_SUCCEED = "USERS_REQUEST_SUCCEED";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCEED = "DELETE_USER_SUCCEED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCEED = "UPDATE_USER_SUCCEED";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCEED = "ADD_USER_SUCCEED";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
